### ISSUE TITLE
hostNetwork in kubernetes config not saved

### ISSUE THREAD

**Issue by T1mey** [SAP/devops-docker-cx-server#59] opened 2020-03-30 11:47 UTC
Hello,

we're using v6 of the image. In cloud configuration 

https://jenkins.xyz/configureClouds/

the checkbox Host Network of pod template configuration is not persisted. If we check and save it and come back to the page the field is unchecked again.

**Comment by fwilhe** [comment] 2020-03-30 14:11
Hi @T1mey 

I don't have this page in our Jenkins instance (neither on k8s nor on "plain docker"). Have you installed a custom plugin for that?

**Comment by T1mey** [comment] 2020-03-30 14:14
No, it's the standard. You'll have to create a new cloud. In the cloud a new pod template.

![image](https://user-images.githubusercontent.com/10464878/77922602-8bdc6780-72a1-11ea-8eb3-164f5be06aeb.png)

**Comment by fwilhe** [comment] 2020-03-30 14:59
I don't think we changed anything on purpose with that, it might be caused by an update with Jenkins or one of the plugins that came with a newer image. So if you use `v4` it still works?

**Comment by T1mey** [comment] 2020-03-30 15:06
I haven't tried it out using v4. As well I opened a bug in Jenkins jira.

**Comment by T1mey** [comment] 2020-03-31 06:36
@fwilhe  maybe to describe our problem a bit more in detail.
At the moment we are not able to configure the agents by specifiying the "Raw yaml for the Pod" in the configuration. This yaml is not used.

I'm not sure if in  step exexcuteDockerOnKubernetes / method generatePodSpec

![image](https://user-images.githubusercontent.com/10464878/77994327-14064f80-732a-11ea-9477-ca5e4e69dd96.png)

the config 

![image](https://user-images.githubusercontent.com/10464878/77994684-bcb4af00-732a-11ea-96a6-d2429d6de415.png)

should be read and it's maybe a bug ?

**Comment by fwilhe** [comment] 2020-03-31 07:30
I'm not much familiar with the dockerExecuteOnKubernetes step, maybe @CCFenner, @daniel-kurzynski or @nevskrem  can help here?

**Comment by T1mey** [comment] 2020-03-31 08:23
One remark....

printing config.jenkinsKubernetes to console results in `[:]` (think an empty map)

**Comment by daniel-kurzynski** [comment] 2020-04-02 16:12
`config.jenkinsKubernetes` corresponds to what you have configures in 
```
general:
  jenkinsKubernetes:
  ...
```
in your config.yml

Only specific values from `jenkinsKubernetes` are used (e.g. jnlpAgent, securityContext) and passed into the pod yaml.

As I understand https://itnext.io/dynamic-jenkins-agent-from-kubernetes-4adb98901906 there are multiple ways of defining a podTempalte. One is in the UI (as you are doing it) and then referencing the template by name. (Unfortunately me screen for this looks different than yours, so I am not really sure where your screenshot was taken from.).

But as we are specifying a pod template in every dockerExecuteOnKubernetes and I haven't read anywhere that podTemplates are merged by default, I am wondering why it worked at all. Maybe a change in the Kubernetes plugin?

There is an inheritance mechanism so that you can inherit in your template from another one. Maybe this could be an approach to offer the possibility to configure in jenkinsKubernetes  from which podTemplate the one used in dockerExecuteOnKubernetest should be inherited. 

On additional question: In which context are you using piper? General purpose pipeline, cloud sdk pipeline, steps in a custom pipeline?

**Comment by T1mey** [comment] 2020-04-02 17:37
We are using it for all 3 scenarios. GPP, Cloud SDK as well as simple custom ones.

As well we are using the inherit function of the UI.
We realized now that the flag ist been saved but not displayed properly. Means that if you update the config you must recheck the checkbox otherwise it ist saved as unchecked.

In general the config yaml (especially dnsConfig in our Case) is not recognized by the lib when creating the pod yaml.

**Comment by daniel-kurzynski** [comment] 2020-04-02 19:17
I have tried to implement this idea.

Before I merge, could you please verify that it solves your issue?

In "Manage Jenkins"->"Configure System"->"Cloud" for the cloud "kubernetes" I have created a pod template with the name default and a yaml configuration:
![image](https://user-images.githubusercontent.com/4758527/78273858-addb2180-750f-11ea-98c6-f901631dfa23.png)

You should use the piper version "kubernetes-pods" containing my fix. `library "piper-lib-os@kubernetes-pods"` and use the following configuration:
```
general:
  jenkinsKubernetes:
    verbose: true
    inheritFrom: 'default'
```
With verbose true you should the the complete definition of the podTemplate which is used to create the pod.

Please let me know if it works.

**Comment by T1mey** [comment] 2020-04-06 11:35
I will try to verify asap.

**Comment by T1mey** [comment] 2020-04-06 12:31
So had the time to verify.
It is now correctly merged into the YAML and dnsConfig is appearing.

Just one idea... would'nt it be better to read the Jenkins config and check if the field

![image](https://user-images.githubusercontent.com/10464878/78558548-0f9ed280-7813-11ea-97b2-da66d31df59f.png)

is filled and use that to inject the YAML instead of configuring it via. config.yml?

**Comment by daniel-kurzynski** [comment] 2020-04-06 12:35
I am not aware of an API to check whether this field is set or not. Furthermore, you might have pod pod template configured which you would like to use only in another context.

I will try to merge it into the master as soon as possible.

**Comment by daniel-kurzynski** [comment] 2020-04-08 17:54
It's merged.

**Closed by daniel-kurzynski** 2020-04-08 17:54 UTC
